Users/alsehr/922 pester structural tests
Azure/ResourceModules pull request #1373
Opened 2022-05-08 10:45 UTC by MrMCake

# Description

- Added tests for pipelines to the Pester test file
- Added settings to `settings.json` to enable/disable environment specific tests
- Added documentation to configure the new settings

| Pipeline |
| - |
| [![Storage: StorageAccounts](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml/badge.svg?branch=users%2Falsehr%2F922_pesterStructuralTests)](https://github.com/Azure/ResourceModules/actions/workflows/ms.storage.storageaccounts.yml)|

# Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Wiki)

2022-05-08 19:55 UTC, eriqua requested changes
I'd strongly suggest to avoid asking for another setting to customize. The majority of consumers, if not all, will use only one approach between ADO and GH. 

What about adding the logic in the test itself, to run the ADO and/or the GH tests only if respectively the .azuredevops and/or the .github folders exist? That way we could remove the additional parameters from the settings.json and corresponding wiki instructions. 

Instead, in the wiki, under the static validation, we should specify one sentence or two about the new test.

2022-05-08 20:09 UTC, MrMCake commented
> I'd strongly suggest to avoid asking for another setting to customize. The majority of consumers, if not all, will use only one approach between ADO and GH.
> 
> What about adding the logic in the test itself, to run the ADO and/or the GH tests only if respectively the .azuredevops and/or the .github folders exist? That way we could remove the additional parameters from the settings.json and corresponding wiki instructions.
> 
> Instead, in the wiki, under the static validation, we should specify one sentence or two about the new test.

done

2022-05-09 23:32 UTC, MariusStorhaug commented
Looks good, though the changes added here will only run if a workflow file exists for a module, correct? The idea with the issue that triggered this PR was to add a global pipeline/workflow to check a module compliance without having to rely on pipeline/workflow files existing for a module. I encountered many times that there exist a workflow file, but no pipeline file. That usecase would be covered here, just thinking that it should be independent of the module-workflow running. It could basically be a status check/validation pipeline triggering on PR if so. i.e. if the contribution matching the "desired module design".

2022-05-10 05:08 UTC, MrMCake commented
> Looks good, though the changes added here will only run if a workflow file exists for a module, correct? The idea with the issue that triggered this PR was to add a global pipeline/workflow to check a module compliance without having to rely on pipeline/workflow files existing for a module. I encountered many times that there exist a workflow file, but no pipeline file. That use case would be covered here, just thinking that it should be independent of the module-workflow running. It could basically be a status check/validation pipeline triggering on PR if so. i.e. if the contribution matching the "desired module design".

Almost. If only checks if a Github or Azure DevOps folder exists respectively. Quite an important detail, as customers will only use one or the other

2022-05-11 18:05 UTC, eriqua commented on utilities/tools/Set-ModuleReadMe.ps1
> -    $TextInfo = (Get-Culture).TextInfo
Is this change intended?

2022-05-11 18:56 UTC, MrMCake commented on arm/.global/global.module.tests.ps1
> +        if (Test-Path (Join-Path $repoRoot '.azuredevops')) {
If I recall correctly, I did test both, yes

2022-05-11 18:56 UTC, MrMCake commented on utilities/tools/Set-ModuleReadMe.ps1
> -    $TextInfo = (Get-Culture).TextInfo
Yes, the variable isn't used

2022-05-12 07:16 UTC, eriqua approved these changes
🆗

2022-05-12 07:16 UTC, merged