[Docs]: Updated solution examples in Wiki
Azure/ResourceModules pull request #1375
Opened 2022-05-08 14:47 UTC by MrMCake

# Description

- Updated solution examples in Wiki
  - Added 'details' blocks
  - Added 'How to start' block

Depends on #1362  

# Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update (Wiki)

2022-05-08 16:26 UTC, eriqua submitted a review, later dismissed
If depending on another PR can this be put in Draft or at least have automerge disabled?

2022-05-29 21:05 UTC, MariusStorhaug requested changes

2022-05-29 21:05 UTC, MariusStorhaug commented on docs/wiki/Solution creation.md
> +| DevOps Self-Hosted | [link](https://github.com/Azure/DevOps-Self-Hosted) | - Create & maintain images with a pipeline using the Azure Image Builder service <p> - Deploy & maintain Azure DevOps Self
```suggestion
| Repository | Description |
| - | - |
| [AVD Accelerator](https://github.com/Azure/avdaccelerator) | AVD Accelerator deployment automation to simplify the setup of AVD (Azure Virtual Desktop) |
| [AKS Baseline Automation](https://github.com/Azure/aks-baseline-automation) | Repository for the AKS Landing Zone Accelerator program's Automation reference implementation |
| [DevOps Self-Hosted](https://github.com/Azure/DevOps-Self-Hosted) | - Create & maintain images with a pipeline using the Azure Image Builder service <p> - Deploy & maintain Azure DevOps Self-Hosted agent pools with a pipeline using Virtual Machine Scale Set|
```

2022-05-29 22:26 UTC, MariusStorhaug approved these changes

2022-05-29 22:30 UTC, merged