review the home page & the context pages, punctuation, consolidate images
Azure/ResourceModules pull request #1463
Opened 2022-06-02 06:00 UTC by matebarabas

# Description

This is meant to be an overarching review and update of the wiki documentation and its lingo, in preparation of adding more content.

This is a draft PR, as the work has just begun, but I'd like to be as transparent as possible.

# Type of Change

- [x] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (readme)
- [ ] I did format my code

2022-06-09 15:47 UTC, matebarabas commented on docs/wiki/Solution creation.md
Yep, I figured out already. :) Will do.

2022-06-15 16:31 UTC, MariusStorhaug requested changes
First round of feedback

2022-06-15 19:02 UTC, MariusStorhaug commented on docs/wiki/Contribution guide - Contribution flow.md
> +- [Open a PR](#open-a-pr)
```suggestion
- [Create or pick up an issue](#create-or-pick-up-an-issue)
- [Environment setup](#environment-setup)
- [Implement the contribution](#implement-the-contribution)
- [Validate the contribution](#Validate-the-contribution)
- [Open a PR](#Open-a-pr)
```

2022-06-16 14:45 UTC, matebarabas commented on docs/wiki/Home.md
> +  - [**Scenario 3:** Contribute](./Getting%20started%20-%20Scenario%203%20Contribute.md)
Swapped.

2022-06-16 14:45 UTC, matebarabas commented on docs/wiki/The context - CARML CI environment.md
CI environment definition added.

2022-06-17 10:17 UTC, eriqua commented on docs/wiki/Known issues.md
> +  - [Microsoft.Network/vpnSites](#microsoftnetworkvpnsites)
Just a heads-up for pulling latest changes as we just merged an update to this page.

2022-06-20 22:00 UTC, MariusStorhaug commented on docs/wiki/The CI environment - Deployment validation.md
Agreed to take this feedback to a new issue, and close the point in the PR.

2022-06-20 22:01 UTC, merged