[Modules] DocumentDB - Add enable free tier tag to cosmos db properties
Azure/ResourceModules pull request #3128
Opened 2023-04-20 07:17 UTC by samuelya

# Description

Added enablefreetier to properties of cosmos db to allow the deployment of cosmos db using free tier which will be useful for the development environment

Fixes: #3125 

> List any dependencies that are required for this change.

## Pipeline references
> For module/pipeline changes, please create and attach the status badge of your successful run.

| Pipeline |
| - |
| [![DocumentDB - DatabaseAccounts](https://github.com/samuelya/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml/badge.svg?branch=users%2Fsamg%2FenableFreeTierForCosmosDb)](https://github.com/samuelya/ResourceModules/actions/workflows/ms.documentdb.databaseaccounts.yml)|

# Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

2023-04-20 07:23 UTC, samuelya commented
@microsoft-github-policy-service agree

2023-04-22 03:16 UTC, ahmadabdalla commented
@samuelya thanks for your contribution. Can you please attach a successful pipeline/workflow run for the change? Happy to support you if you need assistance in that.

2023-04-23 23:40 UTC, samuelya commented
> @samuelya thanks for your contribution. Can you please attach a successful pipeline/workflow run for the change? Happy to support you if you need assistance in that.

Hi @ahmadabdalla Do I need to run the test on my own Azure subscription first using my own pipelines? Is that what you mean?

2023-04-24 06:37 UTC, ahmadabdalla requested changes
Thanks @samuelya  :) And thanks for attaching the pipeline run. I've added a suggestion, can you please review. Also would require regenerating the documentation. Thanks

2023-04-24 06:37 UTC, ahmadabdalla commented on modules/Microsoft.DocumentDB/databaseAccounts/deploy.bicep
> +@description('Optional. Enable free tier.')
```suggestion
@description('Optional. Flag to indicate whether Free Tier is enabled.')
```

2023-04-25 07:07 UTC, ahmadabdalla approved these changes

2023-04-25 07:08 UTC, merged