Release/installPatches
Azure/ResourceModules pull request #3956
Opened 2023-09-12 15:52 UTC by jdrepo

# Description

Based on #3954 

</details>

Support for the "installPatches" property in the Microsoft.Maintenance/maintenanceConfigurations resource

### Pipeline references

| Pipeline |
| - |
|[![Maintenance - MaintenanceConfigurations](https://github.com/jdrepo/ResourceModules/actions/workflows/ms.maintenance.maintenanceconfigurations.yml/badge.svg)](https://github.com/jdrepo/ResourceModules/actions/workflows/ms.maintenance.maintenanceconfigurations.yml) |

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update to documentation

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (readme)
- [ ] I did format my code

2023-09-12 16:01 UTC, AlexanderSehr requested changes
Looks great. 2 asks though:
- Please also update the readme using our Set-ModuleReadme utility
- If possible, it would also be great if we could add the usage of the parameter to the common test case (which would also need a subsequent update of the Readme). This helps us to make sure the change works and further is a good reference for the community on how the object must look like

2023-09-12 18:56 UTC, jdrepo commented
Added missing module README.md and modified common test case. Can you have a look please ?

Another common question: How can I assign the follwong labels to PR:

-  [cat] modules 
- enhancement

2023-09-12 20:39 UTC, AlexanderSehr commented
> Added missing module README.md and modified common test case. Can you have a look please ?
> 
> Another common question: How can I assign the follwong labels to PR:
> 
> * [cat] modules
> * enhancement

You don't, but I just did. Will review shortly :)

2023-09-12 20:39 UTC, AlexanderSehr commented on modules/maintenance/maintenance-configuration/.test/common/main.test.bicep
> +
```suggestion
```

2023-09-12 20:43 UTC, AlexanderSehr commented
Looks great. Just 1 comment, then we can merge. Thanks @jdrepo

2023-09-13 09:53 UTC, AlexanderSehr approved these changes

2023-09-13 09:53 UTC, AlexanderSehr commented
Here we go. Thanks @jdrepo

2023-09-13 09:53 UTC, merged

2023-09-13 10:11 UTC, jdrepo commented
Thanks. 
What will happen to the referenced issue #3954  in the Product backlog ? 
Will it be closed automatically or should I close it by myself ?