[CI environment] Add nameprefix to rg test names
Azure/ResourceModules pull request #4038
Opened 2023-10-01 13:44 UTC by eriqua

# Description

Add nameprefix to rg test names, aligning with avm pbr names

### Pipeline references

| Pipeline |
| - |
| |

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update to documentation

## Checklist

- [ ] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (readme)
- [ ] I did format my code

2023-10-01 13:51 UTC, AlexanderSehr commented
@eriqua, I believe we have a few cases where a name prefix doesn't exist (by design). Once I'm back at my laptop, I can run a quick test by compiling all test cases in memory

2023-10-01 21:52 UTC, eriqua commented
> @eriqua, I believe we have a few cases where a name prefix doesn't exist (by design). Once I'm back at my laptop, I can run a quick test by compiling all test cases in memory

In that case we'd probably need to add it wherever an RG is created as part of the dependencies.

2023-10-01 21:59 UTC, AlexanderSehr requested changes
Found warnings/errors
- ERROR: C:\dev\ip\Azure-ResourceModules\ResourceModules\modules\managed-identity\user-assigned-identity\.test\min\main.test.bicep(9,41) : Error BCP057: The name "namePrefix" does not exist in the current context.
- WARNING: C:\dev\ip\Azure-ResourceModules\ResourceModules\modules\db-for-postgre-sql\flexible-server\.test\public\main.test.bicep(19,7) : Warning no-unused-params: Parameter "password" is declared but never used. [https://aka.ms/bicep/linter/no-unused-params]
- ERROR: C:\dev\ip\Azure-ResourceModules\ResourceModules\modules\resources\tags\.test\rg\main.test.bicep(9,41) : Error BCP057: The name "namePrefix" does not exist in the current context.

2023-10-22 17:50 UTC, eriqua commented
Closing in favor of #4130

2023-10-22 17:50 UTC, closed without merging