Added armDeployment composite action
Azure/ResourceModules pull request #44
Opened 2021-09-15 23:09 UTC by ahmadabdalla

# Change

Added a custom action to deploy templates across different scopes

## Type of Change

- [x ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (readme)
- [ ] I did format my code

2021-09-16 07:05 UTC, MrMCake commented
Small suggestion: 

By fetching the Schema from the ARM template you could automatically determine the scope. One param less to cover ;) As a reference, check line 95 in this [script](https://github.com/MrMCake/Modules/blob/main/.github/actions/templates/deployModule/scripts/New-ModuleDeployment.ps1) out. 

Also I'd recommend to move the content of the step into a dedicated script as it makes testing easier and allows you to re-use the code for other purposes.

2021-09-17 04:03 UTC, ahmadabdalla commented
@MrMCake ready for review

2021-09-24 06:53 UTC, ahmadabdalla commented
@MrMCake @segraef 

Updated the following: New-ModuleDeployment.ps1 

- Added 'additionalTags' as an optional input. Allows injecting info from the pipeline as tags (i.e. commit id). 
- Support for multiple files as input (comma separated).
- Support for directory-based path (filters for .json files). 
- Support for retry (2 times - 5 seconds apart).
- Moved the 'removeDeployment' logic before the deployment.

Questions:
- Do we need the 'moduleName' parameter? 
- Do we need the 'removeDeployment' parameter?

2021-09-24 08:02 UTC, MrMCake requested changes

2021-09-24 08:43 UTC, ahmadabdalla commented on .github/actions/templates/deployModule/scripts/New-ModuleDeployment.ps1
> +        foreach ($file in $parameterFilePath) {
Addressed

2021-09-24 08:44 UTC, ahmadabdalla commented on .github/actions/templates/deployModule/scripts/New-ModuleDeployment.ps1
> +            while ($Stoploop -eq $false) {
Added upper limit as an (or) and added optional parameter, default is 3

2021-09-24 08:44 UTC, ahmadabdalla commented on .github/actions/templates/deployModule/scripts/New-ModuleDeployment.ps1
> +            Write-Verbose "Deploying: $($fileProperties.Name) `n"
Resolved

2021-09-24 08:47 UTC, MrMCake approved these changes

2021-09-24 08:47 UTC, MrMCake commented on .github/actions/templates/deployModule/scripts/New-ModuleDeployment.ps1
> +            Write-Verbose "Deploying: $($fileProperties.Name) `n"
Approved

2021-09-24 08:47 UTC, MrMCake commented on .github/actions/templates/deployModule/scripts/New-ModuleDeployment.ps1
> +        foreach ($file in $parameterFilePath) {
Approved

2021-09-24 08:48 UTC, MrMCake commented on .github/actions/templates/deployModule/scripts/New-ModuleDeployment.ps1
> +            while ($Stoploop -eq $false) {
Approved

2021-09-24 11:54 UTC, merged