Create MOVED-TO-AVM.md
Azure/ResourceModules pull request #4482
Opened 2024-02-05 16:20 UTC by moisesjgomez

# Description

Moved to AVM. Updated Readme. 

Issue: https://github.com/Azure/ResourceModules/issues/4476

https://github.com/Azure/bicep-registry-modules/pull/832

2024-02-05 17:58 UTC, AlexanderSehr requested changes
Note, this require and update for the Readme as well. Like in AVM, please run the `utilities/tools/Set-Module.ps1` script on the module folder

2024-02-06 17:03 UTC, moisesjgomez commented
> Note, this require and update for the Readme as well. Like in AVM, please run the `utilities/tools/Set-Module.ps1` script on the module folder

Readme updated.

2024-02-06 17:21 UTC, ChrisSidebotham approved these changes

2024-02-06 21:58 UTC, AlexanderSehr approved these changes

2024-02-06 21:58 UTC, merged