Users/yimengyuan/privatednsrefactored
Azure/ResourceModules pull request #495
Opened 2021-11-18 16:02 UTC by Yimyames

# Change
- Refactored module to child resource structure
- Updated parameter file
- Updated documentation

Pipeline reference
[![Network: Privatednszones](https://github.com/Yimyames/ResourceModules/actions/workflows/ms.network.privatednszones.yml/badge.svg?branch=users%2Fyimengyuan%2Fprivatednsrefactored)](https://github.com/Yimyames/ResourceModules/actions/workflows/ms.network.privatednszones.yml)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Wiki)

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

2021-11-21 11:08 UTC, MariusStorhaug requested changes
Looking really good, seeing this is the first contribution!

2021-11-21 11:08 UTC, MariusStorhaug commented on arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/deploy.bicep
> +}
Check this with Alex. Not sure we have decided on this being the structure we want to go with yet. Before that decision is made, I would suggest that we keep it to the current way of doing this. @MrMCake What's your take on this? Should we not stay with the current agreement, while having the 2 module that POC the other approaches leaving the rest in line?

Current way of implementing this: <https://github.com/Azure/ResourceModules/blob/main/arm/Microsoft.Compute/virtualMachines/extensions/deploy.bicep#L47>

Issue describing the change, where no decision has been made, before we do the restructuring of modules:
https://github.com/Azure/ResourceModules/issues/480

2021-11-22 09:59 UTC, MrMCake commented on arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/deploy.bicep
> +}
Hey @MariusStorhaug, should be fine here. We used the same in for example AutomationAccount. On this level it does not require any special treatment. Hence I'd keep it here

2021-11-22 10:00 UTC, MrMCake commented on arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
> +                        "e58511af-4da2-449c-a5cd-6a10271cfb83"
Good catch. We also use them in EventHub by the way. @Yimyames can you update the Id as described by @MariusStorhaug and re-run the pipeline?

2021-11-22 13:46 UTC, Yimyames commented on arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
> +                        "e58511af-4da2-449c-a5cd-6a10271cfb83"
Hi @MariusStorhaug, thanks for the review. I tested the token, it does not work yet - the ID works though.

2021-11-22 13:56 UTC, MariusStorhaug commented on arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
> +                        "e58511af-4da2-449c-a5cd-6a10271cfb83"
Did you integrate latest changes from upstream main? I see that it should be available from the upstream:main branch:
https://github.com/Azure/ResourceModules/blob/main/.github/actions/templates/deployModule/action.yml#L63

2021-11-22 13:57 UTC, MariusStorhaug commented on arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
> +                        "e58511af-4da2-449c-a5cd-6a10271cfb83"
Could also be that the variable needs to be added to your own fork/environment.
Docs on this seems to be somewhere here:
https://github.com/Azure/ResourceModules/blob/main/docs/wiki/GettingStarted.md#L213

2021-11-22 13:57 UTC, MariusStorhaug commented on arm/Microsoft.Network/privateDnsZones/virtualNetworkLinks/deploy.bicep
> +}
Ok!

2021-11-22 13:58 UTC, MariusStorhaug commented on arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
> +                        "e58511af-4da2-449c-a5cd-6a10271cfb83"
Could also be that the variable needs to be added to your own fork/environment.
Docs on this seems to be somewhere here:
https://github.com/Azure/ResourceModules/blob/main/docs/wiki/GettingStarted.md#L213

2021-11-23 09:44 UTC, MrMCake commented on arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
> +                        "e58511af-4da2-449c-a5cd-6a10271cfb83"
Hey @MariusStorhaug , as this [PR](https://github.com/Azure/ResourceModules/pull/500) isn't merged yet, this won't work. @Yimyames tested it too and it did indeed fail

2021-11-25 08:10 UTC, MariusStorhaug commented on arm/Microsoft.Network/privateDnsZones/.parameters/parameters.json
> +                        "e58511af-4da2-449c-a5cd-6a10271cfb83"
right, so that needs to come later. Agreed

2021-11-25 08:13 UTC, MariusStorhaug approved these changes
All of my comments are resolved. Approved

2021-11-25 08:13 UTC, merged