Users/sogangul/bicep add multi repo solution - Publish Wiki Guidelines for Multi-repo Orchestration with CARML
Azure/ResourceModules pull request #999
Opened 2022-02-14 16:06 UTC by SomilGanguly

# Change

***Feel free to remove this sample text***
>Thank you for your contribution !

Publishing wiki guidelines to use Multi-Repo Orchestration with Carml Modules

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update (Wiki)

## Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] I did format my code

2022-02-14 20:49 UTC, MrMCake requested changes
Let's have a discussion about that one some time. There are a few points I'd like to discuss

2022-02-18 09:45 UTC, MrMCake commented on docs/wiki/ModulesUsage.md
> +- [Solution deployment](#solution-deployment)
Let's move under `Orchestrate deployment / Pipeline-orchestration / Multi-Repository-Approach`

2022-02-18 09:54 UTC, MrMCake commented on docs/wiki/ModulesUsage.md
> +>    | Sr. no. | Topic| IaCS | CARML |
Remove table

2022-02-18 10:15 UTC, MrMCake commented on docs/wiki/ModulesUsage.md
> +        1. Checkout 'Azure/ResourceModules' repo at root of the agent
```suggestion
        1. Checkout 'Azure/ResourceModules' repo at root of the agents
```

2022-02-18 11:33 UTC, kavishshivhare commented on docs/wiki/ModulesUsage.md
> +- [Solution deployment](#solution-deployment)
Moved.

2022-02-18 11:33 UTC, kavishshivhare commented on docs/wiki/ModulesUsage.md
> +>    ![IaCS_RGDeployJob](/docs/media/IaCS_DeployRGJob.png)
Removed.

2022-02-18 11:33 UTC, kavishshivhare commented on docs/wiki/ModulesUsage.md
> +>    | Sr. no. | Topic| IaCS | CARML |
Removed.

2022-03-05 22:41 UTC, MrMCake requested changes
Temporarily blocked due to Wiki rework #403 

cc: @eriqua

2022-03-05 22:43 UTC, MrMCake commented on docs/wiki/ModulesUsage.md
> +The bicep modules provided by this repo can also be clubbed together to create more complex infrastructures and in the form a completely reusable solutions or products.
```suggestion
The modules provided by this repo can be orchestrated to create more complex infrastructures and as such reusable solutions or products.
```

2022-03-05 22:47 UTC, MrMCake commented on docs/wiki/ModulesUsage.md
> +## Solution deployment
```suggestion
## Pipeline-orchestration
```

2022-03-05 22:49 UTC, MrMCake commented on docs/wiki/ModulesUsage.md
> +The bicep modules provided by this repo can also be clubbed together to create more complex infrastructures and in the form a completely reusable solutions or products.
Overall, I', not sure if that fit's here. The section should be `Pipeline-orcehstration` and be a counter-part to the explaination what template-orchestration is (above).

Then, there should be a sub-header `# Multi-Repository approach` which explicitely explains this flavor

2022-03-05 22:50 UTC, MrMCake commented on docs/wiki/ModulesUsage.md
> +1. Below is an example which uses a _multi-repository_ approach
```suggestion
1. Below you can find an example which uses makes use of multiple repositories to orchestrat the deployment (also known as a _multi-repository_ approach)
```

2022-03-23 22:19 UTC, MrMCake requested changes
Alright @kavishshivhare, we should be good to redirect the content to the `Soluction creation.md` page. Can you do that?

2022-04-06 12:22 UTC, MrMCake commented on docs/wiki/Solution creation.md
> +The modules provided by this repo can be orchestrated to create more complex infrastructures and as such reusable solutions or products.
We should a few sentences here to explain the idea behind this orchestration option. For example:

```suggestion
The modules provided by this repo can be orchestrated to create more complex infrastructures and as such reusable solutions or products. This approach leverages the main module repository alongside its contained modules & pipeline templates to deploy resources. Each pipeline job deploys one instance of a resources and their order is controlled by specifying dependencies in the pipeline itself. 
```

2022-04-06 13:06 UTC, MrMCake approved these changes

2022-04-06 13:15 UTC, merged